Repository Team-Qampus/Quampus_BE, pull requests merged in 2025-03, with the labels that each got.

#80 [#79]카테고리 타입 추가
  src/main/java/swyp/qampus/category/domain/CategoryType.java
Labels: ♻️refactor

#95 [#94]질문 검색하기 요청 파라미터 수정
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
Labels: 🚑hotfix

#89 [#88]질문 상세보기 수정
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
  src/main/java/swyp/qampus/curious/repository/CuriousRepository.java
  src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java
Labels: ♻️refactor

#83 [#72]홈화면 학과별/학교별 월간 랭킹 비교 조회 구현
  build.gradle
  src/main/generated/swyp/qampus/login/entity/QUser.java
  src/main/generated/swyp/qampus/university/domain/QUniversity.java
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
  src/main/java/swyp/qampus/home/dto/UserHomeDto.java
  src/main/java/swyp/qampus/home/service/HomeServiceImpl.java
  src/main/java/swyp/qampus/login/entity/User.java
  src/main/java/swyp/qampus/login/repository/UserRepository.java
  src/main/java/swyp/qampus/login/repository/UserRepositoryCustom.java
  src/main/java/swyp/qampus/login/repository/UserRepositoryCustomImpl.java
  src/main/java/swyp/qampus/login/service/UserService.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/login/util/JWTFilter.java
  src/main/java/swyp/qampus/university/domain/University.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustom.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
  src/main/java/swyp/qampus/university/service/UniversityService.java
  src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
  src/main/resources/application-test.properties
  src/test/java/swyp/qampus/university/repository/UniversityRepositoryCustomImplTest.java
Labels: ✨feat, 중요도⭐️⭐️⭐️

#98 [#97]질문 생성 시 question_id 응답
  src/main/java/swyp/qampus/question/controller/QuestionController.java
  src/main/java/swyp/qampus/question/domain/CreateQuestionResponseDto.java
  src/main/java/swyp/qampus/question/service/QuestionService.java
  src/main/java/swyp/qampus/question/service/QuestionServiceImpl.java
Labels: ♻️refactor

#103 [Hotfix]Revert 95 94 fix search questions
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
  src/main/java/swyp/qampus/login/controller/UserController.java
  src/main/java/swyp/qampus/login/service/UserService.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix

#107 [#106]healthCheck Controller 추가
  src/main/java/swyp/qampus/test/HealthCheckController.java
Labels: 🐛fix, ✨feat, 중요도⭐️⭐️⭐️

#108 [#106]RestTemplate timeout 설정
  src/main/java/swyp/qampus/ai/config/OpenAiConfig.java
  src/main/java/swyp/qampus/login/config/RestTemplateConfig.java
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix

#109 [#release] v0.0.2
  build.gradle
  src/main/generated/swyp/qampus/login/entity/QUser.java
  src/main/generated/swyp/qampus/university/domain/QUniversity.java
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
  src/main/java/swyp/qampus/answer/domain/AnswerResponseDto.java
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
  src/main/java/swyp/qampus/home/dto/UserHomeDto.java
  src/main/java/swyp/qampus/home/service/HomeServiceImpl.java
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
  src/main/java/swyp/qampus/login/entity/User.java
  src/main/java/swyp/qampus/login/repository/UserRepository.java
  src/main/java/swyp/qampus/login/repository/UserRepositoryCustom.java
  src/main/java/swyp/qampus/login/repository/UserRepositoryCustomImpl.java
  src/main/java/swyp/qampus/login/service/UserService.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/login/util/JWTFilter.java
  src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java
  src/main/java/swyp/qampus/university/domain/University.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustom.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
  src/main/java/swyp/qampus/university/service/UniversityService.java
  src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/swyp/qampus/university/repository/UniversityRepositoryCustomImplTest.java
Labels: 🔖release, 중요도⭐️⭐️⭐️

#114 [#release] v 0.0.2
  src/main/generated/swyp/qampus/login/entity/QUser.java
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java
Labels: 🔖release, 중요도⭐️⭐️⭐️

#115 [#110] build crash
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/login/util/JWTFilter.java
  src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java
  src/main/resources/application.properties
Labels: 🐛fix, 중요도⭐️⭐️⭐️, 🚑hotfix

#117 [#116]jwtfilter 로직 수정
  src/main/java/swyp/qampus/login/util/JWTUtil.java
Labels: 🐛fix, 중요도⭐️⭐️⭐️

#119 [#116]Properties 강제 주입
  src/main/java/swyp/qampus/ai/config/OpenAiConfig.java
  src/main/java/swyp/qampus/common/config/NCPStorageConfig.java
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
Labels: 🐛fix, 중요도⭐️⭐️⭐️

#121 [#120]질문 검색하기 기능 오류 해결
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
Labels: 🚑hotfix

#124 [#123]verification system of gpt
  src/main/java/swyp/qampus/ai/service/AiServiceImpl.java
  src/main/java/swyp/qampus/ai/verification/CheckQuestionVerificationService.java
  src/main/java/swyp/qampus/ai/verification/CheckQuestionVerificationServiceImpl.java
  src/main/resources/application.properties
Labels: ✨feat, 중요도⭐️

#126 [#125]대학교별 최신 활동 내역 5개 조회
  src/main/generated/swyp/qampus/activity/QActivity.java
  src/main/generated/swyp/qampus/activity/dto/QRecentActivityResponseDto.java
  src/main/generated/swyp/qampus/university/domain/QUniversity.java
  src/main/java/swyp/qampus/activity/Activity.java
  src/main/java/swyp/qampus/activity/ActivityType.java
  src/main/java/swyp/qampus/activity/controller/ActivityController.java
  src/main/java/swyp/qampus/activity/dto/RecentActivityResponseDto.java
  src/main/java/swyp/qampus/activity/repository/ActivityCustomRepository.java
  src/main/java/swyp/qampus/activity/repository/ActivityCustomRepositoryImpl.java
  src/main/java/swyp/qampus/activity/repository/ActivityRepository.java
  src/main/java/swyp/qampus/activity/service/ActivityService.java
  src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
  src/main/java/swyp/qampus/login/config/data/RedisCustomService.java
  src/main/java/swyp/qampus/login/config/data/RedisCustomServiceImpl.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/question/service/QuestionServiceImpl.java
  src/main/java/swyp/qampus/university/domain/University.java
  src/main/java/swyp/qampus/university/repository/UniversityRepository.java
  src/main/resources/application.properties
Labels: 🐛fix, ✨feat, 중요도⭐️⭐️⭐️

#127 [#125]ActivityController Swagger 업데이트
  src/main/java/swyp/qampus/activity/controller/ActivityController.java
  src/main/java/swyp/qampus/activity/dto/RecentActivityResponseDto.java
Labels: 중요도⭐️⭐️⭐️, 📕docs

#128 [#125]UniversityDetail 500 오류 fix
  src/main/java/swyp/qampus/university/controller/UniversityController.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
  src/main/java/swyp/qampus/university/service/UniversityService.java
  src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
Labels: 🐛fix, 중요도⭐️⭐️

#130 [#129]university의 latitude,longitude 반환
  .gitignore
  src/main/generated/swyp/qampus/university/domain/QUniversity.java
  src/main/java/swyp/qampus/login/controller/OAuthController.java
  src/main/java/swyp/qampus/login/controller/UserController.java
  src/main/java/swyp/qampus/login/service/CompleteSignupService.java
  src/main/java/swyp/qampus/login/service/UserService.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/openApi/GetLocationUtil.java
  src/main/java/swyp/qampus/openApi/LocationDto.java
  src/main/java/swyp/qampus/openApi/UniversityLocationResponse.java
  src/main/java/swyp/qampus/test/TestController.java
  src/main/java/swyp/qampus/university/controller/UniversityController.java
  src/main/java/swyp/qampus/university/domain/University.java
  src/main/java/swyp/qampus/university/domain/response/UniversityRankResponseDto.java
  src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
  src/main/resources/application-secret.properties
  src/main/resources/application.properties
Labels: ✨feat, 중요도⭐️⭐️⭐️

#133 [#129]activity/detail 토큰 제거
  src/main/java/swyp/qampus/activity/controller/ActivityController.java
  src/main/java/swyp/qampus/activity/service/ActivityService.java
  src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java
  src/main/java/swyp/qampus/university/domain/response/UniversityRankResponseDto.java
Labels: 🐛fix, 중요도⭐️⭐️⭐️

#135 [#134]Answer create시 answerId반환
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
  src/main/java/swyp/qampus/answer/service/AnswerService.java
  src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
Labels: ♻️refactor, 중요도⭐️

#137 [#134]대학교 존재하지 않을 시 빈 배열 반환
  src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java
Labels: ♻️refactor, 중요도⭐️⭐️

#138 [#release] v 0.0.2
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
  src/main/java/swyp/qampus/login/controller/OAuthController.java
  src/main/java/swyp/qampus/login/service/OauthService.java
  src/main/java/swyp/qampus/login/service/impl/OauthServiceImpl.java
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/login/util/JWTUtil.java
  src/test/java/swyp/qampus/login/LogoutControllerTest.java
Labels: 🔖release, 중요도⭐️⭐️

#141 [#140]longitude,latitude 순서 변경
  src/main/java/swyp/qampus/university/domain/response/UniversityRankResponseDto.java
Labels: ♻️refactor, 중요도⭐️

#144 [#140]학교 이름 수정
  src/main/java/swyp/qampus/ai/service/AiServiceImpl.java
  src/main/java/swyp/qampus/university/controller/UniversityController.java
  src/main/java/swyp/qampus/university/domain/University.java
  src/main/java/swyp/qampus/university/service/UniversityService.java
  src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
Labels: ✨feat, 중요도⭐️⭐️

#146 [#145]university detail enhancement
  src/main/java/swyp/qampus/image/service/ImageServiceImpl.java
  src/main/java/swyp/qampus/login/service/CompleteSignupService.java
  src/main/java/swyp/qampus/test/TestController.java
Labels: ♻️refactor, 중요도⭐️⭐️

#148 refact:test user생성 시 대학교 존재여부 수정
  src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
  src/main/java/swyp/qampus/openApi/GetLocationUtil.java
  src/main/java/swyp/qampus/university/domain/University.java
Labels: ♻️refactor, 중요도⭐️⭐️

#149 refat:답변 생성 시 반환 Dto 변경
  src/main/java/swyp/qampus/answer/controller/AnswerController.java
  src/main/java/swyp/qampus/answer/domain/CreateAnswerResponseDto.java
  src/main/resources/application.properties
Labels: ♻️refactor, 중요도⭐️⭐️

#150 fix:답변 생성 시 반환 dto 수정
  src/main/java/swyp/qampus/answer/domain/CreateAnswerResponseDto.java
Labels: 🐛fix
