Repository Team-Qampus/Quampus_BE, pull requests merged in 2025-02, with the labels that each got.

#44 [#39]docker compose 작성
  docker-compose.yml
  src/main/java/swyp/qampus/login/util/JWTUtil.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: 중요도⭐️⭐️, 👷cicd

#47 [#46]jenkins 파일 및 Docker-compose 파일 수정
  Jenkinsfile
  build.gradle
  docker-compose.yml
Labels: 🐛fix, 중요도⭐️⭐️⭐️, 👷cicd

#48 [#46]java-21설정
  build.gradle
Labels: 🐛fix, 중요도⭐️⭐️

#49 [#46]java-21설정
  Jenkinsfile
Labels: 📌chore, 중요도⭐️⭐️, 👷cicd

#50 [#46]java-17설정
  build.gradle
Labels: 중요도⭐️, 👷cicd

#51 [#46]Docker-compose설정
  docker-compose.yml
Labels: 중요도⭐️⭐️, 👷cicd

#54 [#52]cros 오류 해결
  src/main/java/swyp/qampus/answer/domain/AnswerWeeklyResponseDto.java
  src/main/java/swyp/qampus/home/controller/HomeController.java
  src/main/java/swyp/qampus/home/dto/HomeResponseDto.java
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
  src/main/java/swyp/qampus/login/repository/UserRepository.java
  src/main/java/swyp/qampus/login/util/JWTUtil.java
  src/main/java/swyp/qampus/question/domain/MyQuestionResponseDto.java
  src/main/java/swyp/qampus/question/domain/QuestionWeeklyResponseDto.java
  src/main/resources/application-secret.properties
  src/main/resources/application.properties
Labels: 🐛fix, 중요도⭐️⭐️⭐️

#56 [#52]Jenkins 파일 수정
  Jenkinsfile
  docker-compose.yml
Labels: 🐛fix, 중요도⭐️⭐️, 👷cicd

#61 [#60]카카오 로그인 오류 수정 master 브랜치 병합
  build.gradle
  src/main/java/swyp/qampus/login/config/ModuleConfig.java
  src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java
  src/main/java/swyp/qampus/login/controller/OAuthController.java
  src/main/java/swyp/qampus/login/converter/OAuthConverter.java
  src/main/java/swyp/qampus/login/converter/UserConverter.java
  src/main/java/swyp/qampus/login/entity/User.java
  src/main/java/swyp/qampus/login/service/CompleteSignupService.java
  src/main/resources/application.properties
Labels: 🔀branch

#64 [#63]package 재성정
  src/main/java/swyp/qampus/curious/repository/CuriousCustomRepositoryImpl.java
  src/main/resources/application.properties
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix

#69 [#68]Jenkins,docker-compose.yml 수정
  Jenkinsfile
  docker-compose.yml
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix

#71 [#66]회원/비회원 홈 화면 조회 기능 구현
  src/main/java/swyp/qampus/exception/CommonErrorCode.java
  src/main/java/swyp/qampus/home/controller/HomeController.java
  src/main/java/swyp/qampus/home/dto/HomeResponseDto.java
  src/main/java/swyp/qampus/home/dto/UserHomeDto.java
  src/main/java/swyp/qampus/home/service/HomeService.java
  src/main/java/swyp/qampus/home/service/HomeServiceImpl.java
  src/main/resources/application.properties
Labels: ✨feat, 중요도⭐️⭐️⭐️

#85 [#84]랭킹 토큰 파라미터 제거
  src/main/java/swyp/qampus/university/controller/UniversityController.java
  src/main/java/swyp/qampus/university/service/UniversityService.java
  src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix

#91 [#90]my.cnf 추가
  docker-compose.yml
  my.cnf
Labels: 중요도⭐️⭐️, 📕docs

#93 [#92]ChoiceRequestDto @NoArgsConstructor 추가
  src/main/java/swyp/qampus/answer/domain/ChoiceRequestDto.java
  src/main/java/swyp/qampus/university/domain/response/UniversityDetailResponseDto.java
Labels: 중요도⭐️⭐️⭐️, 🚑hotfix
